services:
  app:
    build:
      context: ./docker/app
    container_name: smbc_learning_dev
    volumes:
      - .:/workspace
    working_dir: /workspace
    environment:
      APP_ENV: development
      CUDA_LAUNCH_BLOCKING: 1
      PYTORCH_CUDA_ALLOC_CONF: max_split_size_mb:128
    command: ["tail", "-f", "/dev/null"]
    tty: true
    stdin_open: true
    
    # GPU設定のみ
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    
    # 不要な設定を全削除:
    # - healthcheck
    # - restart policy  
    # - networks (defaultで十分)
    # - memory limits (開発時は制限なし)