# Spanish electricity price prediction - Holiday and festival configuration (2015-2018)

# City coordinates information
cities:
  coordinates:
    Madrid: [40.4168, -3.7033]
    Barcelona: [41.3851, 2.1686]
    Valencia: [39.4699, -0.3756]
    Sevilla: [37.3891, -5.9845]
    Bilbao: [43.2627, -2.9253]

# Population weights configuration (2015-2018 period estimates)
population_weights:
  # Pattern A: Administrative area population base
  admin_population:
    Madrid: 3200000     # Approx 3.2M people
    Barcelona: 1600000  # Approx 1.6M people
    Valencia: 790000    # Approx 790K people
    Sevilla: 690000     # Approx 690K people
    Bilbao: 352000      # Approx 352K people (2015-2018 actual)
    
  # Pattern B: Metropolitan area population base
  metro_population:
    Madrid: 6500000     # Madrid metro area approx 6.5M people
    Barcelona: 5200000  # Barcelona metro area approx 5.2M people
    Valencia: 1700000   # Valencia metro area approx 1.7M people
    Sevilla: 1400000    # Sevilla metro area approx 1.4M people
    Bilbao: 950000      # Bilbao metro area approx 950K people

# Spanish national holidays (2015-2018)
national_holidays:
  2015:
    "2015-01-01": "New Year's Day"
    "2015-01-06": "Epiphany (Three Kings Day)"
    "2015-04-03": "Good Friday"
    "2015-05-01": "Labor Day"
    "2015-08-15": "Assumption of Mary"
    "2015-10-12": "Hispanic Day (National Day)"
    "2015-11-01": "All Saints Day"
    "2015-12-06": "Constitution Day"
    "2015-12-08": "Immaculate Conception"
    "2015-12-25": "Christmas Day"
    
  2016:
    "2016-01-01": "New Year's Day"
    "2016-01-06": "Epiphany (Three Kings Day)"
    "2016-03-25": "Good Friday"
    "2016-05-01": "Labor Day"
    "2016-08-15": "Assumption of Mary"
    "2016-10-12": "Hispanic Day (National Day)"
    "2016-11-01": "All Saints Day"
    "2016-12-06": "Constitution Day"
    "2016-12-08": "Immaculate Conception"
    "2016-12-25": "Christmas Day"
    
  2017:
    "2017-01-01": "New Year's Day"
    "2017-01-06": "Epiphany (Three Kings Day)"
    "2017-04-14": "Good Friday"
    "2017-05-01": "Labor Day"
    "2017-08-15": "Assumption of Mary"
    "2017-10-12": "Hispanic Day (National Day)"
    "2017-11-01": "All Saints Day"
    "2017-12-06": "Constitution Day"
    "2017-12-08": "Immaculate Conception"
    "2017-12-25": "Christmas Day"
    
  2018:
    "2018-01-01": "New Year's Day"
    "2018-01-06": "Epiphany (Three Kings Day)"
    "2018-03-30": "Good Friday"
    "2018-05-01": "Labor Day"
    "2018-08-15": "Assumption of Mary"
    "2018-10-12": "Hispanic Day (National Day)"
    "2018-11-01": "All Saints Day"
    "2018-12-06": "Constitution Day"
    "2018-12-08": "Immaculate Conception"
    "2018-12-25": "Christmas Day"

# Major festivals information (2015-2018)
festivals:
  # Semana Santa (Holy Week) - dates vary by year based on Easter
  semana_santa:
    2015:
      start_date: "2015-03-29"  # Palm Sunday
      end_date: "2015-04-05"    # Easter Sunday
      primary_cities: ["Sevilla", "Valencia"]
      scale: "large"
      outdoor_rate: 0.7
      
    2016:
      start_date: "2016-03-20"
      end_date: "2016-03-27"
      primary_cities: ["Sevilla", "Valencia"]
      scale: "large"
      outdoor_rate: 0.7
      
    2017:
      start_date: "2017-04-09"
      end_date: "2017-04-16"
      primary_cities: ["Sevilla", "Valencia"]
      scale: "large"
      outdoor_rate: 0.7
      
    2018:
      start_date: "2018-03-25"
      end_date: "2018-04-01"
      primary_cities: ["Sevilla", "Valencia"]
      scale: "large"
      outdoor_rate: 0.7

  # Feria de Abril (Seville Spring Festival)
  feria_abril:
    2015:
      start_date: "2015-04-21"
      end_date: "2015-04-26"
      primary_cities: ["Sevilla"]
      scale: "medium"
      outdoor_rate: 0.8
      
    2016:
      start_date: "2016-04-12"
      end_date: "2016-04-17"
      primary_cities: ["Sevilla"]
      scale: "medium"
      outdoor_rate: 0.8
      
    2017:
      start_date: "2017-05-02"
      end_date: "2017-05-07"
      primary_cities: ["Sevilla"]
      scale: "medium"
      outdoor_rate: 0.8
      
    2018:
      start_date: "2018-04-17"
      end_date: "2018-04-22"
      primary_cities: ["Sevilla"]
      scale: "medium"
      outdoor_rate: 0.8

  # San Fermin Festival (Pamplona Running of the Bulls)
  san_fermin:
    2015:
      start_date: "2015-07-06"
      end_date: "2015-07-14"
      primary_cities: ["Bilbao"]  # Basque region representative
      scale: "medium"
      outdoor_rate: 0.9
      
    2016:
      start_date: "2016-07-06"
      end_date: "2016-07-14"
      primary_cities: ["Bilbao"]
      scale: "medium"
      outdoor_rate: 0.9
      
    2017:
      start_date: "2017-07-06"
      end_date: "2017-07-14"
      primary_cities: ["Bilbao"]
      scale: "medium"
      outdoor_rate: 0.9
      
    2018:
      start_date: "2018-07-06"
      end_date: "2018-07-14"
      primary_cities: ["Bilbao"]
      scale: "medium"
      outdoor_rate: 0.9

  # La Tomatina (Tomato Festival)
  la_tomatina:
    2015:
      start_date: "2015-08-26"
      end_date: "2015-08-26"
      primary_cities: ["Valencia"]
      scale: "small"
      outdoor_rate: 1.0
      
    2016:
      start_date: "2016-08-31"
      end_date: "2016-08-31"
      primary_cities: ["Valencia"]
      scale: "small"
      outdoor_rate: 1.0
      
    2017:
      start_date: "2017-08-30"
      end_date: "2017-08-30"
      primary_cities: ["Valencia"]
      scale: "small"
      outdoor_rate: 1.0
      
    2018:
      start_date: "2018-08-29"
      end_date: "2018-08-29"
      primary_cities: ["Valencia"]
      scale: "small"
      outdoor_rate: 1.0

  # Reyes Magos (Three Kings Day) Parade
  reyes_magos_parade:
    2015:
      start_date: "2015-01-05"
      end_date: "2015-01-05"
      primary_cities: ["Madrid", "Barcelona", "Valencia", "Sevilla", "Bilbao"]
      scale: "large"
      outdoor_rate: 0.6
      
    2016:
      start_date: "2016-01-05"
      end_date: "2016-01-05"
      primary_cities: ["Madrid", "Barcelona", "Valencia", "Sevilla", "Bilbao"]
      scale: "large"
      outdoor_rate: 0.6
      
    2017:
      start_date: "2017-01-05"
      end_date: "2017-01-05"
      primary_cities: ["Madrid", "Barcelona", "Valencia", "Sevilla", "Bilbao"]
      scale: "large"
      outdoor_rate: 0.6
      
    2018:
      start_date: "2018-01-05"
      end_date: "2018-01-05"
      primary_cities: ["Madrid", "Barcelona", "Valencia", "Sevilla", "Bilbao"]
      scale: "large"
      outdoor_rate: 0.6

# Feature engineering configuration
feature_engineering:
  # Distance decay parameters
  distance_decay:
    max_distance_km: 400  # Zero influence at this distance
    half_effect_distance_km: 200  # 50% effect at this distance
    
  # Base impact by festival scale
  scale_impact:
    small: 0.1
    medium: 0.3
    large: 0.6
    
  # Time-based effects
  time_effects:
    preparation_days_before: 3  # Preparation period (days before)
    aftermath_days_after: 2     # Cleanup period (days after)
    evening_start_hour: 19      # Evening start time
    evening_end_hour: 23        # Evening end time
    
  # Interaction settings
  interactions:
    holiday_amplification_factor: 1.5  # Effect amplification on holidays
    rain_threshold_mm: 5.0              # Rain threshold for outdoor event reduction
    indoor_displacement_rate: 0.3       # Indoor conversion rate
    weekday_afternoon_reduction: -0.2   # Weekday afternoon power reduction rate
    weekday_evening_increase: 0.3       # Weekday evening power increase rate

# LASSO feature selection configuration
feature_selection:
  max_features: 15
  cv_folds: 5
  alpha_range:
    min: 1e-4
    max: 1.0
    num_alphas: 50
  multicollinearity_threshold: 30  # Condition number threshold
  correlation_threshold: 0.8       # High correlation pair detection threshold